version: '3.8'
x-common:
  database:
    &db-environment
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Panel functionality.
    MYSQL_PASSWORD: &db-password "jkhgghjkjhkgl799786697hjijhikhbjkhjklhu9889hLKJHKGHKGJKhgyh8i7oy789yh9hHKUJIOLqsEShjk"
    MYSQL_ROOT_PASSWORD: "QAszxedwaEDFh0o97985t8ighJiopjkolbnuiyt6787897yhJHOUIKPMNBuhikU8989uidsh89ioioshijohljnkHJGGJiug8y9ou"
  panel:
    &panel-environment
    APP_KEY: "[[{run echo -n 'base64:'; openssl rand -base64 32} and paste in here removing all brackets and leaving quotes]]"
    APP_URL: "https://pt.wr0ng.space"
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "UTC"
    APP_SERVICE_AUTHOR: "wr0ng.alliance@gmail.com"
  mail:
    &mail-environment
    MAIL_FROM: "noreply@example.com"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#

services:

  database:
    image: library/mysql:8.0
    restart: always
    networks:
      - local
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "${DATA_DIR}/database:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"

  cache:
    image: redis:alpine
    restart: always
    networks:
      - local

  panel:
    image: ghcr.io/pterodactyl/panel:v1.9.1
    restart: always
    networks:
      - pterodactyl
      - local
    links:
      - database
      - cache
    volumes:
      - "${DATA_DIR}/panel/var/:/app/var/"
      - "${DATA_DIR}/panel/logs/:/app/storage/logs"
      - "${DATA_DIR}/panel/nginx/:/etc/nginx/conf.d/"
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      TRUSTED_PROXIES: "*"
    labels:
      # HTTP
      - "traefik.http.routers.pterodactyl_panel.entrypoints=web"
      - "traefik.http.routers.pterodactyl_panel.rule=Host(`${PANEL_DOMAIN}`)"
      - "traefik.http.routers.pterodactyl_panel.middlewares=panel_https"
      - "traefik.http.middlewares.panel_https.redirectscheme.scheme=https"
      # HTTPS
      - "traefik.http.routers.pterodactyl_panel-https.entrypoints=websecure"
      - "traefik.http.routers.pterodactyl_panel-https.rule=Host(`${PANEL_DOMAIN}`)"
      - "traefik.http.routers.pterodactyl_panel-https.tls=true"
      - "traefik.http.routers.pterodactyl_panel-https.tls.certresolver=letsencrypt"
      - "traefik.http.services.pterodactyl_panel-https.loadbalancer.server.port=80"

networks:
  local:
    external: false
  pterodactyl:
    external: true
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
